/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GraphicalView.GameConfiguration.RightContainer;

import Controller.ChangeApplicationStateController;
import Events.CreateViewEvent;
import Model.ApplicationState;
import javax.swing.ImageIcon;

/**
 *
 * @author matt
 */
public class RightGameConfigurationPanel extends javax.swing.JPanel {

    /**
     * Creates new form RightGameConfigurationPanel2
     */
    public RightGameConfigurationPanel() {
        initComponents();
    }

    public RightGameConfigurationPanel(CreateViewEvent ev) {
        initComponents();
        initControllers(ev);
        ev.getSender().getEventBusHandler().getEventBus().register(this.playerSelectionItemContainer1);
    }
    
    private void initControllers(CreateViewEvent ev){
        this.mainMenuIcon.addActionListener(new ChangeApplicationStateController(ApplicationState.MainMenu, ev.getSender()));
        this.launchGameIcon.addActionListener(new ChangeApplicationStateController(ApplicationState.Game, ev.getSender()));
    }
    
    public PlayerSelectionItemContainer getPlayerSelectionItemContainer(){
        return this.playerSelectionItemContainer1;
    }

    /**
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon homeIcon = new ImageIcon("./img/GraphicalViewIcon/home-icon.png");
        mainMenuIcon = new javax.swing.JButton(homeIcon);
        ImageIcon goIcon = new ImageIcon("./img/GraphicalViewIcon/go-icon.png");
        launchGameIcon = new javax.swing.JButton(goIcon);
        playerSelectionItemContainer1 = new View.GraphicalView.GameConfiguration.RightContainer.PlayerSelectionItemContainer();

        setBackground(new java.awt.Color(48, 114, 178));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(280, 733));

        mainMenuIcon.setBackground(new java.awt.Color(76, 76, 76));
        mainMenuIcon.setBorder(null);
        mainMenuIcon.setOpaque(true);

        launchGameIcon.setBackground(new java.awt.Color(76, 76, 76));
        launchGameIcon.setBorder(null);
        launchGameIcon.setOpaque(true);

        playerSelectionItemContainer1.setBackground(new java.awt.Color(48, 114, 178));
        playerSelectionItemContainer1.setOpaque(false);

        javax.swing.GroupLayout playerSelectionItemContainer1Layout = new javax.swing.GroupLayout(playerSelectionItemContainer1);
        playerSelectionItemContainer1.setLayout(playerSelectionItemContainer1Layout);
        playerSelectionItemContainer1Layout.setHorizontalGroup(
            playerSelectionItemContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        playerSelectionItemContainer1Layout.setVerticalGroup(
            playerSelectionItemContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playerSelectionItemContainer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mainMenuIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(launchGameIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playerSelectionItemContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 562, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(launchGameIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainMenuIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton launchGameIcon;
    private javax.swing.JButton mainMenuIcon;
    private View.GraphicalView.GameConfiguration.RightContainer.PlayerSelectionItemContainer playerSelectionItemContainer1;
    // End of variables declaration//GEN-END:variables
}
