/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GraphicalView.BoardView.LeftContainer;

import Controller.DecreaseStateController;
import Controller.IncreaseStateController;
import javax.swing.ImageIcon;

/**
 *
 * @author matt
 */
public class CarStateViewItem extends javax.swing.JPanel {

    /**
     * Creates new form CarStateViewItem
     */
    
    
    public CarStateViewItem() {
        initComponents();
    }
    
    public CarStateViewItem(String imgPath, String description){
        this();
        this.jLabel1.setIcon(new ImageIcon(imgPath));
        this.carStateDescription.setText(description);
    }
    
    public void initListenners(IncreaseStateController increaseListenner, DecreaseStateController decreaseListenner){
        this.increaseButton.addActionListener(increaseListenner);
        this.decreaseButton.addActionListener(decreaseListenner);
    }
    
    public void setDescription(String description){
        this.carStateDescription.setText(description);
    }
    
    public void activateButtons(){
        this.increaseButton.setVisible(true);
        this.decreaseButton.setVisible(true);
    }
    
    public void desactivateButtons(){
        this.increaseButton.setVisible(false);
        this.decreaseButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chooseCircuitPanel1 = new View.GraphicalView.GameConfiguration.ChooseCircuitPanel();
        carStateDescription = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ImageIcon img2 = new ImageIcon("./img/controlPanelIcon/minus.png");
        decreaseButton = new javax.swing.JButton(img2);
        ImageIcon img = new ImageIcon("./img/controlPanelIcon/plus.png");
        increaseButton = new javax.swing.JButton(img);

        setBackground(new java.awt.Color(114, 167, 178));
        setMaximumSize(new java.awt.Dimension(160, 37));
        setMinimumSize(new java.awt.Dimension(160, 37));
        setPreferredSize(new java.awt.Dimension(160, 37));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        carStateDescription.setBackground(new java.awt.Color(114, 167, 178));
        carStateDescription.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        carStateDescription.setForeground(new java.awt.Color(255, 255, 255));
        carStateDescription.setText("04 / 15");
        add(carStateDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, 40));

        jLabel1.setBackground(new java.awt.Color(116, 167, 178));
        jLabel1.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel1.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel1.setPreferredSize(new java.awt.Dimension(42, 42));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 35, 35));

        decreaseButton.setBackground(new java.awt.Color(114, 167, 178));
        decreaseButton.setMaximumSize(new java.awt.Dimension(27, 27));
        decreaseButton.setMinimumSize(new java.awt.Dimension(27, 27));
        decreaseButton.setPreferredSize(new java.awt.Dimension(27, 27));
        add(decreaseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 7, -1, -1));

        increaseButton.setBackground(new java.awt.Color(114, 167, 178));
        increaseButton.setMaximumSize(new java.awt.Dimension(27, 27));
        increaseButton.setMinimumSize(new java.awt.Dimension(27, 27));
        increaseButton.setPreferredSize(new java.awt.Dimension(27, 27));
        add(increaseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 6, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel carStateDescription;
    private View.GraphicalView.GameConfiguration.ChooseCircuitPanel chooseCircuitPanel1;
    private javax.swing.JButton decreaseButton;
    private javax.swing.JButton increaseButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
