/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GraphicalView.BoardView.LeftContainer;

import javax.swing.ImageIcon;

/**
 *
 * @author matt
 */
public class InformationsItemView extends javax.swing.JPanel {

    /**
     * Creates new form InformationsItemView
     */
    public InformationsItemView() {
        initComponents();
    }
    
    public InformationsItemView(String imgPath, String desription){
        initComponents();
        this.informationItemContent.setText(desription);
        this.informationItemContent.setLineWrap(true);
        this.informationItemContent.setWrapStyleWord(true);
        this.picture.setIcon(new ImageIcon(imgPath));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        informationItemContent = new javax.swing.JTextArea();
        picture = new javax.swing.JLabel();

        setBackground(new java.awt.Color(114, 167, 178));

        informationItemContent.setEditable(false);
        informationItemContent.setColumns(20);
        informationItemContent.setRows(5);
        jScrollPane1.setViewportView(informationItemContent);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(picture, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(picture, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea informationItemContent;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel picture;
    // End of variables declaration//GEN-END:variables
}
