/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GraphicalView.BoardView.LeftContainer;

import Events.CarPositionChangedEvent;
import Events.CarStatesChangedEvent;
import Events.ChangedClassementEvent;
import Events.CreateViewEvent;
import Events.CurrentPlayerCarSpeedChanged;
import Events.CurrentPlayerChangedEvent;
import Events.CurrentPlayerDiceValueChangedEvent;
import Events.DivinModeChangedEvent;
import Events.GameOverEvent;
import Events.PlayerFinishedALapEvent;
import Events.PlayerIsEliminateEvent;
import Events.PlayerLoosePointsEvent;
import Events.PlayerWonEvent;
import Events.PlayersSortedEvent;
import Events.RuleInformationEvent;
import Events.ScrapOnCellEvent;
import Events.SelectedBendChangedEvent;
import Events.SelectedPlayerChangedEvent;
import Events.ThrowCurrentPlayerDiceEvent;
import View.AbstractFormulaDView;
import View.AbstractGameView;
import com.google.common.eventbus.Subscribe;

/**
 *
 * @author matt
 */
public class MapElementInformationsView extends javax.swing.JPanel implements AbstractFormulaDView, AbstractGameView{

    /**
     * Creates new form MapElementInformations
     */
    public MapElementInformationsView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bendNameLabel = new javax.swing.JLabel();
        numberOfStopsLabel = new javax.swing.JLabel();
        longestPathSize = new javax.swing.JLabel();

        setBackground(new java.awt.Color(114, 167, 178));
        setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        setMaximumSize(new java.awt.Dimension(336, 32767));
        setMinimumSize(new java.awt.Dimension(336, 0));
        setPreferredSize(new java.awt.Dimension(336, 110));

        jPanel1.setBackground(new java.awt.Color(76, 76, 76));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bend informations :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel2.setText("Name :");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel3.setText("Number of stops :");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel4.setText("Longest path size :");

        bendNameLabel.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        bendNameLabel.setText("jLabel5");

        numberOfStopsLabel.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        numberOfStopsLabel.setText("jLabel5");

        longestPathSize.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        longestPathSize.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bendNameLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                        .addComponent(longestPathSize))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(numberOfStopsLabel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bendNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(numberOfStopsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(longestPathSize))
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bendNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel longestPathSize;
    private javax.swing.JLabel numberOfStopsLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void createView(CreateViewEvent ev) {}

    @Override
    public void refreshDice(ThrowCurrentPlayerDiceEvent ev) {}

    @Override
    public void refreshClassement(ChangedClassementEvent ev) {}

    @Override
    public void refreshCarPosition(CarPositionChangedEvent ev) {}

    @Override
    public void refreshCurrentPlayer(CurrentPlayerChangedEvent ev) {}

    @Override
    public void refreshSelectedPlayer(SelectedPlayerChangedEvent ev) {}

    @Override
    public void refreshCurrentPlayerDiceValue(CurrentPlayerDiceValueChangedEvent ev) {}

    @Override
    public void refreshCurrentPlayerCarSpeed(CurrentPlayerCarSpeedChanged ev) {}
    
    @Override
    public void refreshCarStates(CarStatesChangedEvent ev) {
    }

    @Override
    @Subscribe
    public void refreshSelectedBend(SelectedBendChangedEvent ev) {
        this.bendNameLabel.setText(ev.getSelectedBend().getName());
        this.longestPathSize.setText(ev.getSelectedBend().getLongest()+"");
        this.numberOfStopsLabel.setText(ev.getSelectedBend().getMinStop()+"");
   }

    @Override
    public void refreshSortedPlayer(PlayersSortedEvent ev) {}

    @Override
    public void refreshPlayerIsEliminate(PlayerIsEliminateEvent ev) {
    }

    @Override
    public void refreshRuleInformation(RuleInformationEvent ev) {
    }

    @Override
    public void refreshPlayerLoosePoint(PlayerLoosePointsEvent ev) {
    }

    @Override
    public void refreshPlayerFinishedLap(PlayerFinishedALapEvent ev) {
    }

    @Override
    public void refreshPlayerWon(PlayerWonEvent ev) {
    }

    @Override
    public void refreshDivinMode(DivinModeChangedEvent ev) {
    }

    @Override
    public void refreshGameOver(GameOverEvent ev) {
    }

    @Override
    public void refreshCell(ScrapOnCellEvent ev) {
    }
}
