/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GraphicalView.BoardView.GameOver;

import Controller.ChangeApplicationStateController;
import Controller.CloseApplicationController;
import Events.GameOverEvent;
import Model.ApplicationState;
import Model.Game;
import Model.Players.Player;
import java.awt.FlowLayout;
import java.util.Collection;
import javax.swing.ImageIcon;

/**
 *
 * @author matt
 */
public class GameOverRecapContainer extends javax.swing.JPanel {
    private Game game;

    /**
     * Creates new form GameOverRecapContainer
     */
    public GameOverRecapContainer() {
        initComponents();
    }
    
    private void initControllers(){
        this.menuButton.addActionListener(new ChangeApplicationStateController(ApplicationState.MainMenu, game));
        this.quitButton.addActionListener(new CloseApplicationController(game));
    }

    GameOverRecapContainer(Game game) {
        initComponents();
        this.game = game;
        initControllers();
    }
    
    public void refresh(GameOverEvent ev){
        /*Collection<Player> winPlayers = ev.getGame().getPlayersManager().getWinPlayers();
        Collection<Player> loosePlayers = ev.getGame().getPlayersManager().getLoosePlayers();
        
        for (Player player : winPlayers) {
            this.itemsContainer.add(new GameOverRecapItem(player.getCar().getPictureIconPath(), player.getPlayerName()));
        }
        
        for (Player player : loosePlayers) {
            this.itemsContainer.add(new GameOverRecapItem(player.getCar().getPictureIconPath(), player.getPlayerName()));
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        quitButton = new View.GraphicalView.FormulaDButtons.FormulaDWarningButton();
        menuButton = new View.GraphicalView.FormulaDButtons.FormulaDDefaultButton();
        ImageIcon icon = new ImageIcon("./img/GraphicalViewIcon/flag.png");
        jLabel2 = new javax.swing.JLabel(icon);
        jLabel3 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(600, 250));
        setMinimumSize(new java.awt.Dimension(600, 250));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(600, 250));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 45)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GAME OVER");
        jLabel1.setToolTipText("");

        quitButton.setText("Quitter");

        menuButton.setText("Menu");
        menuButton.setMaximumSize(new java.awt.Dimension(118, 29));
        menuButton.setMinimumSize(new java.awt.Dimension(118, 29));

        jLabel2.setMaximumSize(new java.awt.Dimension(128, 128));
        jLabel2.setMinimumSize(new java.awt.Dimension(128, 128));
        jLabel2.setPreferredSize(new java.awt.Dimension(128, 128));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Thanks to have played ! ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(menuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private View.GraphicalView.FormulaDButtons.FormulaDDefaultButton menuButton;
    private View.GraphicalView.FormulaDButtons.FormulaDWarningButton quitButton;
    // End of variables declaration//GEN-END:variables
}
