/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GraphicalView.GameConfiguration;

import Controller.ChangeAILevelCurrentComputerPlayer;
import Events.ApplicationStateChangedEvent;
import Events.CircuitAddedEvent;
import Events.CircuitChangedEvent;
import Events.CreateViewEvent;
import Events.CurrentPlayerCarChangedEvent;
import Events.CurrentPlayerChangedEvent;
import Events.CurrentPlayerModeChangedEvent;
import Events.NumberOfPlayersChanged;
import Events.PlayerNameChangedEvent;
import Events.WeatherChangedEvent;
import View.AbstractFormulaDConfigurationGameView;
import View.AbstractFormulaDView;
import com.google.common.eventbus.Subscribe;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author matt
 */
public class ChoosePresetsGame extends javax.swing.JPanel implements AbstractFormulaDConfigurationGameView, AbstractFormulaDView {

    private boolean isConnect = true;

    /**
     * Creates new form Test
     */
    public ChoosePresetsGame() {
        initComponents();
    }
    
    
    private void initListenners(final CreateViewEvent ev) {
        this.addCircuitButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ChooseCircuitfileChooser c = new ChooseCircuitfileChooser(ev.getSender());
                JFrame j = new JFrame();
                j.add(c);
                j.pack();
                j.setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        circuitNameLabel = new javax.swing.JLabel();
        addCircuitButton = new View.GraphicalView.FormulaDButtons.FormulaDWarningButton("New Circuit");
        ImageIcon icon2 = new ImageIcon("./img/GraphicalViewIcon/user-group.png"
        );
        jLabel9 = new javax.swing.JLabel(icon2);
        ImageIcon icon = new ImageIcon("./img/GraphicalViewIcon/circuit-icon.png");
        jLabel10 = new javax.swing.JLabel(icon);
        ImageIcon icon3 = new ImageIcon("./img/GraphicalViewIcon/informations.png");
        jLabel11 = new javax.swing.JLabel(icon3);
        jLabel12 = new javax.swing.JLabel();
        chooseNumberOfPlayersPanel1 = new View.GraphicalView.GameConfiguration.ChooseNumberOfPlayersPanel();
        chooseCircuitPanel = new View.GraphicalView.GameConfiguration.ChooseCircuitPanel();
        jLabel4 = new javax.swing.JLabel();
        chooseWeatherPanel1 = new View.GraphicalView.GameConfiguration.ChooseWeatherPanel();
        ImageIcon weatherIcon = new ImageIcon("./img/GraphicalViewIcon/weather-icon.png");
        WeatherIcon = new javax.swing.JLabel(weatherIcon);

        jButton1.setText("jButton1");

        setBackground(new java.awt.Color(69, 69, 69));
        setForeground(new java.awt.Color(255, 255, 255));
        setAutoscrolls(true);
        setMaximumSize(new java.awt.Dimension(306, 809));
        setMinimumSize(new java.awt.Dimension(306, 809));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Number Of Player :");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Choose Circuit :");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name : ");

        circuitNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        circuitNameLabel.setText("Monaco");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Circuit Informations :");

        chooseNumberOfPlayersPanel1.setBackground(new java.awt.Color(69, 69, 69));
        chooseNumberOfPlayersPanel1.setForeground(new java.awt.Color(255, 255, 255));

        chooseCircuitPanel.setBackground(new java.awt.Color(69, 69, 69));

        javax.swing.GroupLayout chooseCircuitPanelLayout = new javax.swing.GroupLayout(chooseCircuitPanel);
        chooseCircuitPanel.setLayout(chooseCircuitPanelLayout);
        chooseCircuitPanelLayout.setHorizontalGroup(
            chooseCircuitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        chooseCircuitPanelLayout.setVerticalGroup(
            chooseCircuitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );

        jLabel4.setBackground(new java.awt.Color(69, 69, 69));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Weather :");

        chooseWeatherPanel1.setBackground(new java.awt.Color(69, 69, 69));
        chooseWeatherPanel1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout chooseWeatherPanel1Layout = new javax.swing.GroupLayout(chooseWeatherPanel1);
        chooseWeatherPanel1.setLayout(chooseWeatherPanel1Layout);
        chooseWeatherPanel1Layout.setHorizontalGroup(
            chooseWeatherPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        chooseWeatherPanel1Layout.setVerticalGroup(
            chooseWeatherPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chooseNumberOfPlayersPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chooseCircuitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(WeatherIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12)
                            .addComponent(addCircuitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(95, 95, 95)
                                .addComponent(circuitNameLabel))
                            .addComponent(jLabel4)
                            .addComponent(chooseWeatherPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chooseNumberOfPlayersPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chooseCircuitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel12)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(circuitNameLabel))
                .addGap(18, 18, 18)
                .addComponent(addCircuitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(WeatherIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chooseWeatherPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel WeatherIcon;
    private View.GraphicalView.FormulaDButtons.FormulaDWarningButton addCircuitButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private View.GraphicalView.GameConfiguration.ChooseCircuitPanel chooseCircuitPanel;
    private View.GraphicalView.GameConfiguration.ChooseNumberOfPlayersPanel chooseNumberOfPlayersPanel1;
    private View.GraphicalView.GameConfiguration.ChooseWeatherPanel chooseWeatherPanel1;
    private javax.swing.JLabel circuitNameLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollBar jScrollBar1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void refreshApplicationState(ApplicationStateChangedEvent ev) {
    }

    @Override
    public void refreshWeather(WeatherChangedEvent ev) {
    }

    @Override
    public void refreshCurrentPlayer(CurrentPlayerChangedEvent ev) {
    }

    @Override
    public void refreshNumberOfPlayers(NumberOfPlayersChanged ev) {
    }

    @Override
    @Subscribe
    public void refreshCircuitAdded(CircuitAddedEvent ev) {
        System.out.println("test");
        this.chooseCircuitPanel.refreshCircuitAdded(ev);
    }

    @Override
    public void refreshPlayerName(PlayerNameChangedEvent ev) {
    }

    @Override
    public void refreshCurrentCar(CurrentPlayerCarChangedEvent ev) {
    }

    @Override
    public void refreshCurrentPlayerMode(CurrentPlayerModeChangedEvent ev) {
    }

    @Override
    public void refreshCurrentComputerPlayerLevel(ChangeAILevelCurrentComputerPlayer ev) {
    }

    @Override
    public boolean isConnect() {
        return this.isConnect;
    }

    @Override
    public void connectView() {
        this.isConnect = true;
    }

    @Override
    public void disconnectView() {
        this.isConnect = false;
    }

    @Override
    public void createView(CreateViewEvent ev) {
        initListenners(ev);
        ev.getSender().getEventBusHandler().getEventBus().register(chooseCircuitPanel);
        this.chooseNumberOfPlayersPanel1.initListenners(ev);
        this.chooseCircuitPanel.initPanel(ev);
        this.chooseWeatherPanel1.initPanel(ev);
        this.circuitNameLabel.setText(ev.getSender().getCircuit().getName());
    }

    @Override
    public void refreshCircuit(CircuitChangedEvent ev) {
        this.circuitNameLabel.setText(ev.getCircuit().getName());
    }
}
