/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GraphicalView.GameConfiguration;

import Controller.ChangeAILevelCurrentComputerPlayer;
import Controller.ChangeHumanModeController;
import Events.ApplicationStateChangedEvent;
import Events.CircuitAddedEvent;
import Events.CircuitChangedEvent;
import Events.CreateViewEvent;
import Events.CurrentPlayerCarChangedEvent;
import Events.CurrentPlayerChangedEvent;
import Events.CurrentPlayerModeChangedEvent;
import Events.NumberOfPlayersChanged;
import Events.PlayerNameChangedEvent;
import Events.WeatherChangedEvent;
import Model.AILevels;
import Model.Players.ComputerPlayer;
import Model.Players.HumanPlayer;
import Model.Players.Player;
import View.AbstractFormulaDConfigurationGameView;
import View.AbstractFormulaDView;
import com.google.common.eventbus.Subscribe;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;

/**
 *
 * @author matt
 */
public class CurrentPlayerConfiguration extends javax.swing.JPanel implements AbstractFormulaDConfigurationGameView, AbstractFormulaDView {

    boolean isConnect;
    private ModifyCarCaracteristicsFrame modifyCarConfigurationFrame;

    /**
     * Creates new form Test3
     */
    public CurrentPlayerConfiguration() {
        initComponents();
        this.modifyCarConfigurationFrame = new ModifyCarCaracteristicsFrame();
    }

    public CurrentPlayerConfiguration(CreateViewEvent ev) {
        this();
        /*
         * Initialisation des controleurs
         */
        initControllers(ev);
        ev.getSender().getEventBusHandler().addFormulaDView(this.carManagerPanel, ev.getSender());
        ev.getSender().getEventBusHandler().addFormulaDView(this.modifyCarConfigurationFrame, ev.getSender());
    }

    private void initControllers(final CreateViewEvent ev) {
        final CurrentPlayerConfiguration newThis = this;
        this.CurrentPlayerTextField.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
            }

            @Override
            public void keyPressed(KeyEvent e) {
            }

            @Override
            public void keyReleased(KeyEvent e) {
                ev.getSender().getPlayersManager().getCurrentPlayer().setName(newThis.CurrentPlayerTextField.getText());
            }
        });

        this.CurrentPlayerTextField.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (ev.getSender().getPlayersManager().getCurrentPlayer().getPlayerName().equals("")) {
                    ev.getSender().getPlayersManager().getCurrentPlayer().setName(Player.getNextDefaultPlayerName());
                }
            }
        });
        this.HumanPlayerRadioButton.addActionListener(new ChangeHumanModeController(ev.getSender(), true));
        this.ComputerPlayerRadioButton.addActionListener(new ChangeHumanModeController(ev.getSender(), false));
        this.BegginerRadioButton.addActionListener(new ChangeAILevelCurrentComputerPlayer(ev.getSender(), AILevels.Beginner));
        this.showModifyCaracteristicsCarButton.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                modifyCarConfigurationFrame.setLocationRelativeTo(null);
                modifyCarConfigurationFrame.setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CurrentPlayerTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ImageIcon icon = new ImageIcon("./img/GraphicalViewIcon/configure-icon.png");
        jLabel3 = new javax.swing.JLabel(icon);
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BegginerRadioButton = new javax.swing.JRadioButton();
        carManagerPanel = new View.GraphicalView.GameConfiguration.ChooseCarPanel();
        jLabel7 = new javax.swing.JLabel();
        ComputerPlayerRadioButton = new javax.swing.JRadioButton();
        HumanPlayerRadioButton = new javax.swing.JRadioButton();
        showModifyCaracteristicsCarButton = new View.GraphicalView.FormulaDButtons.FormulaDWarningButton();

        setBackground(new java.awt.Color(48, 114, 178));
        setBorder(null);
        setOpaque(false);

        jLabel1.setBackground(new java.awt.Color(48, 114, 178));
        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Player Configuration");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pseudo :");

        jLabel4.setBackground(new java.awt.Color(48, 114, 178));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Player Type :");

        jLabel6.setBackground(new java.awt.Color(48, 114, 178));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("AI Level :");

        BegginerRadioButton.setBackground(new java.awt.Color(48, 114, 178));
        BegginerRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        BegginerRadioButton.setText("Begginer");

        jLabel7.setBackground(new java.awt.Color(48, 114, 178));
        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Choose an available car :");

        ComputerPlayerRadioButton.setBackground(new java.awt.Color(48, 114, 178));
        ComputerPlayerRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        ComputerPlayerRadioButton.setText("Computer player");
        ComputerPlayerRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComputerPlayerRadioButtonActionPerformed(evt);
            }
        });

        HumanPlayerRadioButton.setBackground(new java.awt.Color(48, 114, 178));
        HumanPlayerRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        HumanPlayerRadioButton.setText("Human player");

        showModifyCaracteristicsCarButton.setText("Modify car's caracteristics");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BegginerRadioButton)
                                    .addComponent(ComputerPlayerRadioButton)
                                    .addComponent(HumanPlayerRadioButton)
                                    .addComponent(CurrentPlayerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(86, 86, 86)))
                        .addGap(223, 223, 223)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(showModifyCaracteristicsCarButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(carManagerPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel2))
                            .addComponent(CurrentPlayerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ComputerPlayerRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(HumanPlayerRadioButton)))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BegginerRadioButton)
                            .addComponent(jLabel6))))
                .addGap(36, 36, 36)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(carManagerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(showModifyCaracteristicsCarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ComputerPlayerRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComputerPlayerRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComputerPlayerRadioButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BegginerRadioButton;
    private javax.swing.JRadioButton ComputerPlayerRadioButton;
    private javax.swing.JTextField CurrentPlayerTextField;
    private javax.swing.JRadioButton HumanPlayerRadioButton;
    private View.GraphicalView.GameConfiguration.ChooseCarPanel carManagerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private View.GraphicalView.FormulaDButtons.FormulaDWarningButton showModifyCaracteristicsCarButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void createView(CreateViewEvent ev) {
        ButtonGroup levelButtonGroup = new ButtonGroup();
        levelButtonGroup.add(BegginerRadioButton);

        ButtonGroup playerModeGroup = new ButtonGroup();
        playerModeGroup.add(ComputerPlayerRadioButton);
        playerModeGroup.add(HumanPlayerRadioButton);
    }

    @Override
    @Subscribe
    public void refreshApplicationState(ApplicationStateChangedEvent ev) {
    }

    @Override
    @Subscribe
    public void refreshWeather(WeatherChangedEvent ev) {
    }

    @Override
    @Subscribe
    public void refreshCurrentPlayer(CurrentPlayerChangedEvent ev) {
        Player currentPlayer = ev.getCurrentPlayer();
        if (currentPlayer instanceof HumanPlayer) {
            this.HumanPlayerRadioButton.setSelected(true);
            BegginerRadioButton.setEnabled(false);
        } else {
            this.ComputerPlayerRadioButton.setSelected(true);
            ComputerPlayer currentComputerPlayer = (ComputerPlayer) currentPlayer;
            BegginerRadioButton.setEnabled(true);

        }
        this.CurrentPlayerTextField.setText(currentPlayer.getPlayerName());

    }

    @Override
    @Subscribe
    public void refreshNumberOfPlayers(NumberOfPlayersChanged ev) {
    }

    @Override
    @Subscribe
    public void refreshCircuitAdded(CircuitAddedEvent ev) {
    }

    @Override
    public boolean isConnect() {
        return this.isConnect;
    }

    @Override
    public void connectView() {
        this.isConnect = true;
    }

    @Override
    public void disconnectView() {
        this.isConnect = false;
    }

    @Override
    public void refreshPlayerName(PlayerNameChangedEvent ev) {
        this.CurrentPlayerTextField.setText(ev.getPlayer().getPlayerName());
    }

    @Override
    public void refreshCurrentCar(CurrentPlayerCarChangedEvent ev) {
    }

    @Override
    @Subscribe
    public void refreshCurrentPlayerMode(CurrentPlayerModeChangedEvent ev) {
        if (ev.getPlayer() instanceof ComputerPlayer) {
            ComputerPlayer computPlayer = (ComputerPlayer)ev.getPlayer();
            if (computPlayer.getLevel() == AILevels.Beginner) {
                this.BegginerRadioButton.setSelected(true);
            }
        }
    }

    @Override
    public void refreshCurrentComputerPlayerLevel(ChangeAILevelCurrentComputerPlayer ev) {
    }

    @Override
    public void refreshCircuit(CircuitChangedEvent ev) {
    }
}
