/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GraphicalView.ScoresView;

import Controller.ChangeApplicationStateController;
import Controller.NextScoreController;
import Controller.PreviousScoreController;
import Events.CreateViewEvent;
import Events.CurrentScoreChangedEvent;
import Model.ApplicationState;
import javax.swing.ImageIcon;

/**
 *
 * @author matt
 */
public class ScoresViewPanel extends javax.swing.JPanel{

    /**
     * Creates new form ScoresViewPanel
     */
    public ScoresViewPanel() {
        initComponents();
    }
    
    public ScoresViewPanel(CreateViewEvent ev){
        initComponents();
        initControllers(ev);
        this.winPlayerPanel.createView(ev);
        this.loosePlayerPanel.createView(ev);
        this.circuitNameLabel.setText(ev.getSender().getScoresManager().getCurrentScore().getCircuitName());
        this.dateLabel.setText(ev.getSender().getScoresManager().getCurrentScore().getDate().toString());
        ev.getSender().getEventBusHandler().getEventBus().register(this);
    }
    
    private void initControllers(CreateViewEvent ev){
        this.homeButton.addActionListener(new ChangeApplicationStateController(ApplicationState.MainMenu, ev.getSender()));
        this.rightArrowButton.addActionListener(new NextScoreController(ev.getSender().getScoresManager()));
        this.leftArrowButton.addActionListener(new PreviousScoreController(ev.getSender().getScoresManager()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ImageIcon trophee = new ImageIcon("./img/GraphicalViewIcon/trophee.png");
        tropheeIcon = new javax.swing.JLabel(trophee);
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        circuitNameLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        ImageIcon left = new ImageIcon("./img/GraphicalViewIcon/arrow-left.png");
        leftArrowButton = new javax.swing.JButton(left);
        ImageIcon right = new ImageIcon("./img/GraphicalViewIcon/arrow-right.png");
        rightArrowButton = new javax.swing.JButton(right);
        ImageIcon home = new ImageIcon("./img/GraphicalViewIcon/home-icon.png");
        homeButton = new javax.swing.JButton(home);
        winPlayerPanel = new View.GraphicalView.ScoresView.winPlayersPanel();
        loosePlayerPanel = new View.GraphicalView.ScoresView.LoosePlayersPanel();

        setMaximumSize(new java.awt.Dimension(800, 650));
        setMinimumSize(new java.awt.Dimension(800, 0));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(800, 650));

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SCORES");

        tropheeIcon.setMaximumSize(new java.awt.Dimension(256, 256));
        tropheeIcon.setMinimumSize(new java.awt.Dimension(256, 256));
        tropheeIcon.setPreferredSize(new java.awt.Dimension(256, 256));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Circuit name :");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Date :");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Win Players :");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Loose Players :");

        circuitNameLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        circuitNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        circuitNameLabel.setText("jLabel6");

        dateLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateLabel.setText("jLabel7");

        leftArrowButton.setMaximumSize(new java.awt.Dimension(120, 120));
        leftArrowButton.setMinimumSize(new java.awt.Dimension(120, 120));
        leftArrowButton.setPreferredSize(new java.awt.Dimension(120, 120));

        rightArrowButton.setMaximumSize(new java.awt.Dimension(120, 120));
        rightArrowButton.setMinimumSize(new java.awt.Dimension(120, 120));

        homeButton.setMaximumSize(new java.awt.Dimension(100, 100));
        homeButton.setMinimumSize(new java.awt.Dimension(100, 100));
        homeButton.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout winPlayerPanelLayout = new javax.swing.GroupLayout(winPlayerPanel);
        winPlayerPanel.setLayout(winPlayerPanelLayout);
        winPlayerPanelLayout.setHorizontalGroup(
            winPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        winPlayerPanelLayout.setVerticalGroup(
            winPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout loosePlayerPanelLayout = new javax.swing.GroupLayout(loosePlayerPanel);
        loosePlayerPanel.setLayout(loosePlayerPanelLayout);
        loosePlayerPanelLayout.setHorizontalGroup(
            loosePlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 177, Short.MAX_VALUE)
        );
        loosePlayerPanelLayout.setVerticalGroup(
            loosePlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(leftArrowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154)
                .addComponent(tropheeIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(216, 216, 216))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(279, 279, 279))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(222, 222, 222)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(circuitNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(winPlayerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(248, 248, 248))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                                .addGap(51, 51, 51))
                            .addComponent(loosePlayerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rightArrowButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(174, 174, 174)
                                .addComponent(rightArrowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addComponent(leftArrowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(tropheeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(circuitNameLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(dateLabel))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(winPlayerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(loosePlayerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 307, Short.MAX_VALUE)
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel circuitNameLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton leftArrowButton;
    private View.GraphicalView.ScoresView.LoosePlayersPanel loosePlayerPanel;
    private javax.swing.JButton rightArrowButton;
    private javax.swing.JLabel tropheeIcon;
    private View.GraphicalView.ScoresView.winPlayersPanel winPlayerPanel;
    // End of variables declaration//GEN-END:variables

    public void refreshCurrentScore(CurrentScoreChangedEvent ev){
        this.winPlayerPanel.refresh(ev);
        this.loosePlayerPanel.refresh(ev);
        this.circuitNameLabel.setText(ev.getScore().getCircuitName());
        this.dateLabel.setText(ev.getScore().getDate().toString());
    }


}
